items = [
    {artist: "Kanye West", album: "My Beautiful Dark Twisted Fantasy"},
    {artist: "Arcade Fire", album: "Funeral"},
    {artist: "Frank Ocean", album: "Channel Orange"},
    {artist: "Kanye West", album: "Yeezus"},
    {artist: "Bon Iver", album: "Bon Iver, Bon Iver"},
    {artist: "Kendrick Lamar", album: "good kid, m.A.A.d city"},
    {artist: "Panda Bear", album: "Person Pitch"},
    {artist: "Joanna Newsom", album: "Ys"},
    {artist: "Dizzee Rascal", album: "Boy in Da Corner"},
    {artist: "Madvillain", album: "Madvillainy"},
    {artist: "D'Angelo", album: "Black Messiah"},
    {artist: "Girls", album: "Father, Son, Holy Ghost"},
    {artist: "Radiohead", album: "In Rainbows"},
    {artist: "LCD Soundsystem", album: "Sound of Silver"},
    {artist: "Sun Kil Moon", album: "Benji"},
    {artist: "LCD Soundsystem", album: "This Is Happening"},
    {artist: "Sufjan Stevens", album: "Illinois"},
    {artist: "M83", album: "Dead Cities, Red Seas & Lost Ghosts"},
    {artist: "TV on the Radio", album: "Dear Science"},
    {artist: "Arcade Fire", album: "Reflektor"},
    {artist: "Broken Social Scene", album: "You Forgot It in People"},
    {artist: "M83", album: "Hurry Up, We're Dreaming"},
    {artist: "Beach House", album: "Bloom"},
    {artist: "The Field", album: "From Here We Go Sublime"},
    {artist: "Tame Impala", album: "Lonerism"},
    {artist: "The Flaming Lips", album: "Embryonic"},
    {artist: "Beach House", album: "Teen Dream"},
    {artist: "Fuck Buttons", album: "Tarot Sport"},
    {artist: "Grizzly Bear", album: "Veckatimest"},
    {artist: "Junior Boys", album: "So This Is Goodbye"},
    {artist: "Fleet Foxes", album: "Fleet Foxes"},
    {artist: "James Blake", album: "James Blake"},
    {artist: "Radiohead", album: "Hail to the Thief"},
    {artist: "M.I.A.", album: "Kala"},
    {artist: "Cat Power", album: "You Are Free"},
    {artist: "The Shins", album: "Chutes Too Narrow"},
    {artist: "Toro Y Moi", album: "Underneath the Pine"},
    {artist: "Shabazz Palaces", album: "Black Up"},
    {artist: "The War on Drugs", album: "Lost in the Dream"},
    {artist: "Cut Copy", album: "In Ghost Colours"},
    {artist: "FKA Twigs", album: "LP1"},
    {artist: "Feist", album: "The Reminder"},
    {artist: "Vampire Weekend", album: "Vampire Weekend"},
    {artist: "Flying Lotus", album: "Cosmogramma"},
    {artist: "Spiritualized", album: "Sweet Heart Sweet Light"},
    {artist: "Dirty Projectors", album: "Swing Lo Magellan"},
    {artist: "Fleet Foxes", album: "Helplessness Blues"},
    {artist: "Japandroids", album: "Celebration Rock"},
    {artist: "Real Estate", album: "Atlas"},
    {artist: "PJ Harvey", album: "Let England Shake"},
    {artist: "Youth Lagoon", album: "Wondrous Bughouse"},
    {artist: "Todd Terje", album: "It's Album Time"},
    {artist: "Chromatics", album: "Kill For Love"},
    {artist: "Fleet Foxes", album: "Sun Giant"},
    {artist: "Real Estate", album: "Days"},
    {artist: "Atlas Sound", album: "Parallax"},
    {artist: "The xx", album: "xx"},
    {artist: "The Field", album: "Cupid's Head"},
    {artist: "Ja", album: " - American Gangster"},
    {artist: "Julia Holter", album: "Loud City Song"},
    {artist: "Björk", album: "Vulnicura"},
    {artist: "Cut Copy", album: "Zonoscope"},
    {artist: "Drake", album: "Nothing Was the Same"},
    {artist: "The Walkmen", album: "Lisbon"},
    {artist: "Caribou", album: "Our Love"},
    {artist: "Four Tet", album: "There Is Love in You"},
    {artist: "Vampire Weekend", album: "Contra"},
    {artist: "Jon Hopkins", album: "Immunity"},
    {artist: "Tame Impala", album: "Innerspeaker"},
    {artist: "Flying Lotus", album: "Until the Quiet Comes"},
    {artist: "Cults", album: "Cults"},
    {artist: "Mac DeMarco", album: "Salad Days"},
    {artist: "Gorillaz", album: "Plastic Beach"},
    {artist: "Sonic Youth", album: "Sonic Nurse"},
    {artist: "Daft Punk", album: "Alive 2007"},
    {artist: "Belle And Sebastian", album: "The Life Pursuit"},
    {artist: "The Field", album: "Looping State of Mind"},
    {artist: "Kate Bush", album: "50 Words for Snow"},
    {artist: "How to Dress Well", album: "What Is This Heart?"},
    {artist: "Perfume Genius", album: "Too Bright"},
    {artist: "Real Estate", album: "Real Estate"},
    {artist: "ASAP Rocky", album: "Long. Live. ASAP"},
    {artist: "The Decemberists", album: "The Crane Wife"},
    {artist: "Youth Lagoon", album: "The Year of Hibernation"},
    {artist: "Arcade Fire", album: "Neon Bible"},
    {artist: "Schoolboy Q", album: "Habits & Contradictions"},
    {artist: "The Shins", album: "Port of Morrow"},
    {artist: "Lotus Plaza", album: "Spooky Action at a Distance"},
    {artist: "Devendra Banhart", album: "Rejoicing in the Hands"},
    {artist: "Gonjasufi", album: "A Sufi and a Killer"},
    {artist: "Caribou", album: "Swim"},
    {artist: "Girl Talk", album: "Night Ripper"},
    {artist: "WU LYF", album: "Go Tell Fire to the Mountain"},
];

dorandomthing = function() {
    var item = items[Math.floor(Math.random()*items.length)];
    document.getElementById('pizi').src = 'http://pizi.meteor.com/artists/' + item.artist + '/albums/' + item.album + '/tracks/';
};

